apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      imagePullSecrets:
      - name: docker-secret
      containers:
      - name: config-service
        image: ghcr.io/zzzang12-cns/config-service
        lifecycle:
          preStop:
            exec:
              command: [ "sh", "-c", "sleep 5" ]
        ports:
        - containerPort: 8888